### ISSUE TITLE
Starknet contract deployer

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#24]
Integrate and customize the StarkDeployer by @Dalmasonto into Starknet-Scaffold

https://stark-deployer.vercel.app/production-testnet

**Comment by dalmasonto** [comment]
Hi @Darlington02, will start to work on this

**Comment by Darlington02** [comment]
Hi @dalmasonto all files pertaining to StarkDeployer's UI should please go in here:

https://github.com/argentlabs/Starknet-Scaffold/tree/main/frontend/src/app/components/StarkDeployer

if there are associated contracts, then please create a folder for it in the base folder as is done for the burner wallet

**Comment by dalmasonto** [comment]
Alright
