### ISSUE TITLE
Setup Devnet #ODHack

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#25]
Setup devnet for Starknet, enabling devs spin up a development environment using simple scripts added to the base `package.json`

e.g npm run devnet --args

https://0xspaceshard.github.io/starknet-devnet/docs/intro

Ensure the spun up dev environment is usable with Starknet-Foundry

**Comment by JimmyFate** [comment]
Hey :)
I think I could give this a try
