### ISSUE TITLE
Burner wallet contract #ODHack

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#27]
We want to give users the ability to generate burner wallets which they can fund and play around with for the purpose of development.

Create the contract for the burner wallets should contain a single function that deploys a burner account using OZ's classhash and returns the deployed account address.

NB: the public key arg willl be generated and assigned from the frontend

**Comment by remybar** [comment]
Can I work on it ?

**Comment by Darlington02** [comment]
@remybar I've assigned the issue to you. All contracts related to this issue, should go in here:

https://github.com/argentlabs/Starknet-Scaffold/blob/main/burner/src/lib.cairo
