### ISSUE TITLE
Burner wallet UI #ODHack

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#28]
When the user, visits the burner wallet page, they should see empty fields repeated in 5 places (as max of 5 burner accounts are allowed for each user), e.g: 

### Burner 1
1. private key
2. public key
3. account address

### Burner 2
1. private key
2. public key
3. account address

### Burner 3
1. private key
2. public key
3. account address

### Burner 4
1. private key
2. public key
3. account address

### Burner 5
1. private key
2. public key
3. account address

And a generate wallet button.

When the generate wallet button is clicked, a private key and public key is generated. This button simultaneously deploys a new burner account using the burner account contract and returns an account contract address.

Each generated private key, public key and account address should be stored in local storage.

UI files should go in here:
https://github.com/argentlabs/Starknet-Scaffold/tree/main/frontend/src/app/components/Burner

**Comment by Cheelax** [comment]
I can take it
