### ISSUE TITLE
Scaffold Wikipedia #ODHack

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#29]
Create a table listing all Starknet/Cairo learning resources in the ecosystem. Should go in here:

https://github.com/argentlabs/Starknet-Scaffold/blob/main/frontend/src/app/components/CairoWikipedia/Wikipedia.tsx

**Comment by Maxservais** [comment]
Happy to take this

**Comment by estherbreath** [comment]
Can I also attempt this issue?

**Comment by Maxservais** [comment]
Introduced a PR here: https://github.com/argentlabs/Starknet-Scaffold/pull/32

@Darlington02 there are no merge conflicts, should be good to go: 
![image](https://github.com/argentlabs/Starknet-Scaffold/assets/43566493/76104f0a-fe8e-4d41-8224-720f2a6a4bfb)
