### ISSUE TITLE
Adding PFP and Starknames using `useStarkProfile`

### ISSUE THREAD

**Issue by fricoben** [argentlabs/Starknet-Scaffold#38]
## Description 

Hello ! 

I see that stark domains are integrated into the super cool front-end template. It would be super cool to make the integration deeper by adding PFPs and domain resolving where it lacks [using Starknet React.](https://docs.starknet.id/devs/starknetreact#usestarkprofile)

## Proposed ToDo

- [ ] Add PFP here using the [useStarkProfile hook on Starknet React](https://docs.starknet.id/devs/starknetreact#usestarkprofile) (resolving PFP and domain with one query)

<img width="200" alt="Capture d’écran 2024-03-22 à 12 23 01" src="https://github.com/argentlabs/Starknet-Scaffold/assets/78437165/566b013a-102e-4964-9965-3144873c6a1e">

- [ ] Add PFP and Address here using the same useStarkProfile call

<img width="394" alt="Capture d’écran 2024-03-22 à 12 22 56" src="https://github.com/argentlabs/Starknet-Scaffold/assets/78437165/b619f072-7077-43ae-a225-4cf3cc330efa">

**Comment by raizo07** [comment]
Hello @fricoben can I be assigned to work on this?
