### ISSUE TITLE
Build a UI component for the burner wallet - [React/Nextjs]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#40]
This issue requires you to implement a simple wallet UI component which takes the format of the wireframe below. Should display: 
    1. The burner wallet’s ETH and STRK address (feel free to use dummy values)
    2. The wallet address (feel free to use dummy values)
    3. The send and connect button which opens a modal on click. 

Linked with [the next issue](https://github.com/argentlabs/Starknet-Scaffold/issues/41) 

use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks. Feel free to be creative with the UI.

<img width="634" alt="Screenshot 2024-04-22 at 01 20 22" src="https://github.com/argentlabs/Starknet-Scaffold/assets/75126961/2cc3660c-eb5e-434a-abe0-51419ea20564">

**Comment by Joy-Adah** [comment]
Hi @Darlington02 I'll love to work on this

**Comment by MarvyNwaokobia** [comment]
Hi, I am Marvellous (Smart contract developer and frontend developer). Please can i be assigned this issue?

**Comment by Darlington02** [comment]
@Joy-Adah when building this component, please include an `execute` button alongside the other two buttons
