### ISSUE TITLE
Build modal components for the burner wallet - [React/Nextjs] 

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#41]
Build two modal components for sending supported assets, and inititiating a connection to a burner account. Modal for sending asset should have two inputs and a transfer button:
    1. Wallet address
    2. Amount
    
Modal for initiating a connection should have two inputs:
    1. Private key
    3. Account address
    
Finally, ensure these modals opens up when the “Send” or “Connect” button from [this issue]() is clicked.
    
use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks. Feel free to be creative with the UI.

Sample modal for transferring assets:
<img width="417" alt="Screenshot 2024-04-22 at 01 33 40" src="https://github.com/argentlabs/Starknet-Scaffold/assets/75126961/e961f8eb-2d07-486c-a2ae-ebb41f8b9c40">

**Comment by Oshioke-Salaki** [comment]
Hello please can i be assigned this?

**Comment by Joy-Adah** [comment]
Hi @Darlington02 can I be assigned this?

**Comment by KodeSage** [comment]
Hi @Darlington02 I will love to work on this task?

**Comment by stephanniegb** [comment]
Hey @Darlington02 , I would like to work on this please
