### ISSUE TITLE
Build a UI component for the scaffold deployer - [React/Nextjs]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#43]
This issue requires you to build a UI component for the Scaffold deployer following the wireframe below as a guide.

use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks. Feel free to be creative with the UI.

Ensure to link your component to the landing page

<img width="634" alt="Screenshot 2024-04-22 at 01 20 45" src="https://github.com/argentlabs/Starknet-Scaffold/assets/75126961/831bc909-9f1a-47a8-8dd2-6a15944e89ff">

**Comment by Calebux** [comment]
I want to take up this task!!

**Comment by stephanniegb** [comment]
Hey, I am stephanie, i would like to work on this
