### ISSUE TITLE
Implement the scaffold deployer’s “declare” functionality - [React/Starknetjs]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#44]
This issue requires you to implement the “declare” functionality for the deployer in [this issue](https://github.com/argentlabs/Starknet-Scaffold/issues/43). Takes the contract class JSON file and declares it

Hint: reference the implementation from the smart contract development section on Argent X.

This issue requires a good experience with Starknet.js. use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks.

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by KodeSage** [comment]
Hi @Darlington02 I will love to work on this task

**Comment by Immanuelolivia1** [comment]
I can do this if it has not been assigned

**Comment by princeibs** [comment]
@Darlington02 I believe I can now proceed with this since #43 is merged right?

**Comment by Darlington02** [comment]
Yes, you can
