### ISSUE TITLE
Implement the scaffold deployer’s “deploy” functionality - [React/Starknetjs]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#45]
This issue requires you to implement the “deploy” functionality for the deployer in [this issue](https://github.com/argentlabs/Starknet-Scaffold/issues/43). Takes the contract classhash, and constructor arguments, deploys it, and finally returns the contract address.

Hint: reference the implementation from the smart contract development section on Argent X.

This issue requires a good experience with Starknet.js. use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks.

**Comment by KodeSage** [comment]
Hi @Darlington02 I will love to work on this task
