### ISSUE TITLE
Update the wikipedia section with latest cairo tools and learning resources

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#46]
Update the cairo wikipedia section with latest cairo tools and learning resources. Try to cover every up to date tooling mentioned in the [starknet awesome](https://github.com/keep-starknet-strange/awesome-starknet) page. Skip wallets, ecosystems etc focus on toolings and learning resources that are not already contained in the wikipedia

**Comment by Ugo-X** [comment]
please can i take this?
