### ISSUE TITLE
Add a sample deployment script for deploying cairo contracts [Cairo, SNFoundry]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#48]
A sample deployment script for the cairo contract within the `contract` folder. Goal is to provide a robust template which includes covering alternate deployment means beyond CLI commands.

Reference starknet foundry for more details:
https://foundry-rs.github.io/starknet-foundry/starknet/script.html

**Comment by Jemiiah** [comment]
Can I be
