### ISSUE TITLE
Execute functionality for burner wallet [React/Nextjs/Starknetjs]

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#49]
Create a new modal similar to[ issue 41](https://github.com/argentlabs/Starknet-Scaffold/issues/41) but for executing transactions from the burner wallet. This modal should have input fields to take in the contract address, function selector and constructor arguments, then execute the txn. Ensure the modal is functional.

**Comment by bhavyagosai** [comment]
hey can

**Comment by Dprof-in-tech** [comment]
PLease can this be assigned to me? I would love to work on this.

**Comment by Darlington02** [comment]
Hey @bhavyagosai any updates with this?

**Comment by hardiktheprogrammer** [comment]
@Darlington02  can i work on this, 
Is some one is working on this issue

**Comment by Dprof-in-tech** [comment]
hey @Darlington02 , could i work on this if its not currently being worked on

**Comment by Darlington02** [comment]
@bhavyagosai still on this?
