### ISSUE TITLE
Update deployment feature to support classhashes with constructor arguments

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#65]
The current implementation in the repo, implements deployment for just classhashes with no constructor argument.

This issue requires you to update the implementation for the “deploy” functionality to support classhashes that requires constructor arguments. Takes the contract classhash, and constructor arguments, deploys it, and finally returns the contract address.

Hint: reference the implementation from the smart contract development section on Argent X.

This issue requires a good experience with Starknet.js. use the [telegram group](https://t.me/+sH0ug1mZ_WtjNmM0) to ask questions as regards your assigned tasks.

**Comment by Jemiiah** [comment]
I would like to work on this

**Comment by kateberryd** [comment]
@Darlington02 I would love to work on this

**Comment by BillXJ** [comment]
i want to claim this work
