### ISSUE TITLE
Fix issues with sending ETH/STRK using Burner wallet

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#67]
1. When you send STRK to the Burner wallet, it shows up in a wrong format e.g 2 STRKs shows up as `2000000000000000000.0000STRK` instead of `2.000STRK`. Please fix.

2. When you try sending ETH/STRK from a deployed burner wallet in the current implementation, it fails due to some max_fee error. Please fix.

**Comment by Ayoazeez26** [comment]
Can I work on this?

**Comment by kateberryd** [comment]
I would love to
