### ISSUE TITLE
Switch/display network #ODHack

### ISSUE THREAD

**Issue by Antoine-Sparenberg** [argentlabs/Starknet-Scaffold#7]
A simple button to switch and display connected network. Supported networks should be just mainnet and sepolia. If mainnet, switch to sepolia, if sepolia, switch to mainnet.

Reference:
https://docs.argent.xyz/starknet/argentx/network-switcher-for-dapps

**Comment by faytey** [comment]
can i hop on this?

**Comment by Maxservais** [comment]
Would be interested in taking this forward! Let me know :)
