### ISSUE TITLE
Customizable UI Theme

### ISSUE THREAD

**Issue by Darlington02** [argentlabs/Starknet-Scaffold#79]
Currently, buttons are themed orange as the primary colour, and blue as the secondary. Make this customizable in that from a single file, one can set the primary and secondary color for the buttons. e.g

Primary = "Red"
Secondary = "white"

should make all the buttons across all pages, a mix of red and white. where red will replace the existing orange, and white replace existing blue.

PS: The default setting if not manually tampered with should be the existing orange and blue colors.

**Comment by Ugo-X** [comment]
Good morning . I would love to be assigned this task

**Comment by Oshioke-Salaki** [comment]
can i have this?

**Comment by vibenedict** [comment]
i will like to jump on this issue

**Comment by VictoriaAde** [comment]
Hi, I'm a frontend developer and have a good idea how this can be achieved.
I have 4 years experience.
I would like to work on this

**Comment by mimiprosper** [comment]
Am good in frontend development . I have 4.5yrs experience. I know how this can be done and completed before deadline. Thanks.
