### ISSUE TITLE
App Light/Dark mode #ODHack

### ISSUE THREAD

**Issue by Antoine-Sparenberg** [argentlabs/Starknet-Scaffold#8]

**Comment by codeWhizperer** [comment]
can I take this?

**Comment by Cheelax** [comment]
Gm, I can have a look to this issue

**Comment by Oshioke-Salaki** [comment]
Can I take this

**Comment by Maxservais** [comment]
Would be interested in taking this forward! Let me know :)

**Comment by Antoine-Sparenberg** [comment]
Thanks @codeWhizperer but next time please wait to be assigned the issue 

@Darlington02 will review :)
