### ISSUE TITLE
Typo and Page Title 

### ISSUE THREAD

**Issue by Shoetan** [argentlabs/Starknet-Scaffold#84]
<img width="1440" alt="Screenshot 2024-05-23 at 15 36 56" src="https://github.com/argentlabs/Starknet-Scaffold/assets/17912134/49c2e6c6-cf56-4265-ab8e-473971cb584c">

I think I will make more professional sense to fix this typo and have a custom page title.

I would love to handle this issue if it is a priority

**Comment by Darlington02** [comment]
the buidl was intentional, not a typo:)
