### ISSUE TITLE
Anything that could be useful in STARKNET-SCAFFOLD #ODHack

### ISSUE THREAD

**Issue by Antoine-Sparenberg** [argentlabs/Starknet-Scaffold#9]

**Comment by OkoliEvans** [comment]
How does this work, do I review the code base and suggest a feature or you have some suggestions? In any case, I'm willing to take this up and work on it

**Comment by Darlington02** [comment]
Hey @OkoliEvans yes, please feel free to suggest on the GC, and we'd create an issue for it here. This is more like a suggestion board, but we can create a discussion for it later

**Comment by Cheelax** [comment]
> Heyyy @Darlington02, @Antoine-Sparenberg, i suggest to add:
> 
> * .editorconfig to handle file formatting
> * auto-reconnect wallet on page refresh
> 
> I'm available to work on theses if needed.

agreed on the .editorconfig, would be cool

**Comment by Darlington02** [comment]
Hey @Yubz please feel free to do that:)

**Comment by Yubz** [comment]
Alright, working on this tonight :)

https://github.com/argentlabs/Starknet-Scaffold/issues/18
